name: Docker Build and Push

on:
  push:
    branches:
      - main  # 只在 main 分支推送时触发
    tags:
      - '*'  # 监听所有 tag 推送

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-net-tool:latest .

      - name: Push Docker image
        run: |
          if [[ -n "${{ steps.extract_tag.outputs.tag }}" ]]; then
            TAG=${{ steps.extract_tag.outputs.tag }}
            docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-net-tool:$TAG
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-net-tool:$TAG
          fi
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-net-tool:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-net-tool:latest
